package com.travel.vo.KTO;

import lombok.Data;

@Data
public class KTO_openapi_IntroduceVO {
    private Integer contentid;
    private Integer contenttypeid;
    // 12 관광지
    private String chkpet;
    private String expguide;
    private String infocenter;
    private String opendate;
    private String parking;
    private String restdate;
    private String usetime;
    // 14 문화시설
    private String chkpetculture;
    private String infocenterculture;
    private String parkingculture;
    private String restdateculture;
    private String usefee;
    private String usetimeculture;
    private String spendtime;
    // 15 행사/공연
    private String agelimit;
    private String bookingplace;
    private String eventstartdate;
    private String eventenddate;
    private String eventhomepage;
    private String eventplace;
    private String placeinfo;
    private String playtime;
    private String program;
    private String spendtimefestival;
    private String sponsor1;
    private String sponsor1tel;
    private String sponsor2;
    private String sponsor2tel;
    private String usetimefestival;
    // 25 여행코스
    private String distance;
    private String infocentertourcourse;
    private String schedule;
    private String taketime;
    private String theme;
    // 28 레포츠
    private String chkpetleports;
    private String expagerangeleports;
    private String infocenterleports;
    private String openperiod;
    private String parkingleports;
    private String reservation;
    private String restdateleports;
    private String usefeeleports;
    private String usetimeleports;
    // 32 숙박
    private String accomcountlodging;
    private String checkintime;
    private String checkouttime;
    private String chkcooking;
    private String infocenterlodging;
    private String parkinglodging;
    private String roomcount;
    private String reservationlodging;
    private String reservationurl;
    private String roomtype;
    private String refundregulation;
    // 38 쇼핑
    private String chkpetshopping;
    private String culturecenter;
    private String fairday;
    private String infocentershopping;
    private String opendateshopping;
    private String opentime;
    private String parkingshopping;
    private String restdateshopping;
    private String saleitem;
    private String shopguide;
    // 39 음식점
    private String firstmenu;
    private String infocenterfood;
    private String opendatefood;
    private String opentimefood;
    private String packing;
    private String parkingfood;
    private String reservationfood;
    private String restdatefood;
    private String seat;
    private String treatmenu;
}
